/** Default gallery items served when using in-memory store or empty database. */
export const defaultGallery = [
  {
    _id: "g-campus",
    title: "School Campus",
    description: "A welcoming view of our campus and surroundings.",
    imageUrl: "/images/campus.jpg",
    category: "Campus",
    featured: true,
  },
  {
    _id: "g-library",
    title: "Library",
    description: "A quiet, resource-rich space for reading and study.",
    imageUrl: "/images/library.jpg",
    category: "Library",
    featured: true,
  },
  {
    _id: "g-classroom",
    title: "Classrooms",
    description: "Comfortable, focused learning spaces for students.",
    imageUrl: "/images/classroom.jpg",
    category: "Classrooms",
    featured: false,
  },
  {
    _id: "g-science",
    title: "Science Laboratory",
    description: "Practical experiments that build scientific thinking.",
    imageUrl: "/images/science-lab.jpg",
    category: "Science Lab",
    featured: true,
  },
  {
    _id: "g-computer",
    title: "Computer Laboratory",
    description: "Hands-on learning with modern computing resources.",
    imageUrl: "/images/computer-lab.jpg",
    category: "Computer Lab",
    featured: true,
  },
  {
    _id: "g-img1",
    title: "School Life",
    description: "Moments from Janapath Secondary School.",
    imageUrl: "/images/img1.jpeg",
    category: "Campus",
    featured: false,
  },
  {
    _id: "g-img2",
    title: "Learning Environment",
    description: "Students engaged in daily school activities.",
    imageUrl: "/images/img2.jpeg",
    category: "Classrooms",
    featured: false,
  },
  {
    _id: "g-img3",
    title: "Academic Facilities",
    description: "Spaces that support quality education.",
    imageUrl: "/images/img3.jpeg",
    category: "Campus",
    featured: false,
  },
  {
    _id: "g-img4",
    title: "School Activities",
    description: "Highlights from our school community.",
    imageUrl: "/images/img4.jpeg",
    category: "Events",
    featured: false,
  },
  {
    _id: "g-img5",
    title: "Student Life",
    description: "A vibrant community of learners.",
    imageUrl: "/images/img5.jpeg",
    category: "Students",
    featured: false,
  },
  {
    _id: "g-img6",
    title: "Campus View",
    description: "Janapath Secondary School facilities.",
    imageUrl: "/images/img6.jpeg",
    category: "Campus",
    featured: false,
  },
  {
    _id: "g-img7",
    title: "School Gallery",
    description: "More views of life at Janapath.",
    imageUrl: "/images/img7.jpeg",
    category: "Campus",
    featured: false,
  },
];
